#Program properties
#Tue Dec 12 14:00:25 CET 2023
Pot_za_izvoz_PDF=C\:\\Users\\klemenm\\Desktop\\GitHub\\ControlPlans\\Config\\
Pot_za_izvoz_kontrolnega_lista=C\:\\Users\\klemenm\\Desktop\\GitHub\\ControlPlans\\Config\\
Template_za_kontrolni_list=C\:\\Users\\klemenm\\Desktop\\GitHub\\ControlPlans\\Config\\kontrolni_list_template.xlsx
