#Program properties
#Sun Dec 10 18:45:58 CET 2023
Pot_za_izvoz_PDF=C\:\\Users\\Administrator\\IdeaProjects\\ControlPlanes\\Config\\
Pot_za_izvoz_kontrolnega_lista=C\:\\Users\\Administrator\\IdeaProjects\\ControlPlanes\\Config\\
Template_za_kontrolni_list=C\:\\Users\\Administrator\\IdeaProjects\\ControlPlanes\\Config\\kontrolni_list_template.xlsx
